name: "Hello"

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Who to say hello to"
        required: true
        default: "World"

jobs:
  hello:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          name: ${{ inputs.name }}
